# Generated by Django 5.0.1 on 2024-01-13 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0003_alter_products_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
