# Generated by Django 5.0.1 on 2024-01-13 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0004_delete_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-created_at']},
        ),
    ]
